name: Release to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # PyPI Trusted Publishing
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
      - name: Build sdist/wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build
          ls -l dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No credentials needed with Trusted Publishing