name: Release to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit   # not strictly needed for tests, harmless

  publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for PyPI Trusted Publishing
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # No username/password needed when Trusted Publishing is configured